spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/store-market
      field-creation:
        ignore-class: true


application:
  client:
    ms-products:
      baseUrl: http://localhost:8082/api/v1/products/