openapi: 3.0.0
info:
  title: Microservicio de Productos
  version: 1.0.0
  description: API para obtener productos activos de un cliente.

servers:
  - url: http://localhost:8084
    description: Entorno local

paths:
  /customer-products/customer/{customerId}/active:
    get:
      summary: Obtener productos activos de un cliente
      description: Devuelve una lista de productos activos asociados con un cliente específico.
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
          description: El ID del cliente para el cual se buscan productos.
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Token de autorización en formato 'Bearer <token>'.
      responses:
        200:
          description: Lista de productos activos para el cliente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductResponse'
        401:
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Cliente o productos no encontrados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ProductResponse:
      type: object
      properties:
        id:
          type: string
          description: ID del producto
        name:
          type: string
          description: Nombre del producto
        document_number:
          type: string
          description: Numero de documento del cliente
        description:
          type: string
          description: Descripción del producto
        state:
          type: string
          description: Estado del producto (por ejemplo, "ACTIVO" o "INACTIVO")

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Mensaje de error